### ISSUE TITLE
Create action that contains the common workflows

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-repo-tools#26]
**Problems:**
- Inconsistent linting across repos
- Composer frequently fails due to wporg-mu-plugin changes

**Comment by ryelle** [comment]
Maybe reusable workflows could help? https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by ryelle** [comment]
Reusable workflows seemed promising but were self-contained containers, so we couldn't set up dependencies and build in one workflow, and use that built project in another workflow.

Composite actions seem to be a better approach because we can break apart the common process in each project, while still allowing for customization between steps.
